#ifndef __TETRIS__H
#define __TETRIS__H
#include "wins.h"
#define CELL "\x18\x18"
#define NEXTLINE "\n"
#define SPACE "  "
#define SCREEN_WIDTH 16
#define SCREEN_HIGHT 32

//define state of every picture
//L
const char *L1[]={
	CELL CELL CELL NEXTLINE CELL,
	CELL NEXTLINE CELL NEXTLINE CELL CELL,
	SPACE SPACE CELL NEXTLINE CELL CELL CELL,
	CELL CELL NEXTLINE SPACE CELL NEXTLINE SPACE CELL
};
const char *L2[]={
	CELL CELL CELL NEXTLINE SPACE SPACE CELL,
	SPACE CELL NEXTLINE SPACE CELL NEXTLINE CELL CELL,
	CELL NEXTLINE CELL CELL CELL,
	CELL CELL NEXTLINE CELL NEXTLINE CELL
};
// T
const char *T[]={
	CELL CELL CELL NEXTLINE SPACE CELL NEXTLINE SPACE CELL,
	CELL NEXTLINE CELL CELL CELL NEXTLINE CELL,
	SPACE CELL NEXTLINE SPACE CELL NEXTLINE CELL CELL CELL,
	SPACE SPACE CELL NEXTLINE CELL CELL CELL NEXTLINE SPACE SPACE CELL,
};
//Z
const char * Z1[]={
	CELL CELL NEXTLINE SPACE CELL CELL,
	SPACE CELL NEXTLINE CELL CELL NEXTLINE CELL,
};
const char *Z2[]={
	SPACE CELL CELL NEXTLINE CELL CELL,
	CELL NEXTLINE CELL CELL NEXTLINE SPACE CELL
};
// I
const char *I[]={
	CELL CELL CELL CELL,
	SPACE CELL NEXTLINE SPACE CELL NEXTLINE SPACE CELL NEXTLINE SPACE CELL
};
//square
const char *S[]={//square
	CELL CELL NEXTLINE CELL CELL
};

int L1_matrix[][4][8] ={
	{
		{1,1,1,1,1,1,0,0},
		{1,1,0,0,0,0,0,0},
		{0,0,0,0,0,0,0,0},
		{0,0,0,0,0,0,0,0}
	},
	{
		{1,1,0,0,0,0,0,0},
		{1,1,0,0,0,0,0,0},
		{1,1,1,1,0,0,0,0},
		{0,0,0,0,0,0,0,0}
	},
	{
		{0,0,0,0,1,1,0,0},
		{1,1,1,1,1,1,0,0},
		{0,0,0,0,0,0,0,0},
		{0,0,0,0,0,0,0,0}
	},
	{
		{1,1,1,1,0,0,0,0},
		{0,0,1,1,0,0,0,0},
		{0,0,1,1,0,0,0,0},
		{0,0,0,0,0,0,0,0}
	}
};
#endif
